{"metadata":{"kernelspec":{"language":"python","display_name":"Python 3","name":"python3"},"language_info":{"name":"python","version":"3.7.12","mimetype":"text/x-python","codemirror_mode":{"name":"ipython","version":3},"pygments_lexer":"ipython3","nbconvert_exporter":"python","file_extension":".py"}},"nbformat_minor":4,"nbformat":4,"cells":[{"cell_type":"code","source":"%load_ext autoreload\n%autoreload 2\n!git clone --branch=add-data https://github.com/schmidt-jake/kaggle.git\n%cd kaggle\n!pip install -U pip setuptools wheel\n!pip install -U -r /kaggle/working/kaggle/requirements/main.in","metadata":{"execution":{"iopub.status.busy":"2022-07-19T03:21:48.135240Z","iopub.execute_input":"2022-07-19T03:21:48.135843Z","iopub.status.idle":"2022-07-19T03:23:41.034668Z","shell.execute_reply.started":"2022-07-19T03:21:48.135808Z","shell.execute_reply":"2022-07-19T03:23:41.033473Z"},"trusted":true},"execution_count":3,"outputs":[{"name":"stdout","text":"Cloning into 'kaggle'...\nremote: Enumerating objects: 216, done.\u001b[K\nremote: Counting objects: 100% (216/216), done.\u001b[K\nremote: Compressing objects: 100% (119/119), done.\u001b[K\nremote: Total 216 (delta 99), reused 177 (delta 67), pack-reused 0\u001b[K\nReceiving objects: 100% (216/216), 39.41 KiB | 733.00 KiB/s, done.\nResolving deltas: 100% (99/99), done.\n/kaggle/working/kaggle\nRequirement already satisfied: pip in /opt/conda/lib/python3.7/site-packages (22.1.1)\nCollecting pip\n  Downloading pip-22.1.2-py3-none-any.whl (2.1 MB)\n\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m2.1/2.1 MB\u001b[0m \u001b[31m6.6 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m00:01\u001b[0m00:01\u001b[0m0m\n\u001b[?25hRequirement already satisfied: setuptools in /opt/conda/lib/python3.7/site-packages (59.8.0)\nCollecting setuptools\n  Downloading setuptools-63.2.0-py3-none-any.whl (1.2 MB)\n\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m1.2/1.2 MB\u001b[0m \u001b[31m44.1 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n\u001b[?25hRequirement already satisfied: wheel in /opt/conda/lib/python3.7/site-packages (0.37.1)\nInstalling collected packages: setuptools, pip\n  Attempting uninstall: setuptools\n    Found existing installation: setuptools 59.8.0\n    Uninstalling setuptools-59.8.0:\n      Successfully uninstalled setuptools-59.8.0\n  Attempting uninstall: pip\n    Found existing installation: pip 22.1.1\n    Uninstalling pip-22.1.1:\n      Successfully uninstalled pip-22.1.1\n\u001b[31mERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\ndask-cudf 21.10.1 requires cupy-cuda114, which is not installed.\nbeatrix-jupyterlab 3.1.7 requires google-cloud-bigquery-storage, which is not installed.\ndask-cudf 21.10.1 requires dask==2021.09.1, but you have dask 2022.2.0 which is incompatible.\ndask-cudf 21.10.1 requires distributed==2021.09.1, but you have distributed 2022.2.0 which is incompatible.\u001b[0m\u001b[31m\n\u001b[0mSuccessfully installed pip-22.1.2 setuptools-63.2.0\n\u001b[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\u001b[0m\u001b[33m\n\u001b[0mRequirement already satisfied: kaggle in /opt/conda/lib/python3.7/site-packages (from -r /kaggle/working/kaggle/requirements/main.in (line 1)) (1.5.12)\nRequirement already satisfied: opencv-python in /opt/conda/lib/python3.7/site-packages (from -r /kaggle/working/kaggle/requirements/main.in (line 2)) (4.5.4.60)\nCollecting opencv-python\n  Downloading opencv_python-4.6.0.66-cp36-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (60.9 MB)\n\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m60.9/60.9 MB\u001b[0m \u001b[31m16.9 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m00:01\u001b[0m00:01\u001b[0m\n\u001b[?25hRequirement already satisfied: openslide-python in /opt/conda/lib/python3.7/site-packages (from -r /kaggle/working/kaggle/requirements/main.in (line 3)) (1.2.0)\nRequirement already satisfied: pandas in /opt/conda/lib/python3.7/site-packages (from -r /kaggle/working/kaggle/requirements/main.in (line 4)) (1.3.5)\nRequirement already satisfied: torch in /opt/conda/lib/python3.7/site-packages (from -r /kaggle/working/kaggle/requirements/main.in (line 5)) (1.11.0)\nCollecting torch\n  Downloading torch-1.12.0-cp37-cp37m-manylinux1_x86_64.whl (776.3 MB)\n\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m776.3/776.3 MB\u001b[0m \u001b[31m1.1 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m00:01\u001b[0m00:01\u001b[0m\n\u001b[?25hRequirement already satisfied: torchmetrics in /opt/conda/lib/python3.7/site-packages (from -r /kaggle/working/kaggle/requirements/main.in (line 6)) (0.9.2)\nRequirement already satisfied: torchvision in /opt/conda/lib/python3.7/site-packages (from -r /kaggle/working/kaggle/requirements/main.in (line 7)) (0.12.0)\nCollecting torchvision\n  Downloading torchvision-0.13.0-cp37-cp37m-manylinux1_x86_64.whl (19.1 MB)\n\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m19.1/19.1 MB\u001b[0m \u001b[31m30.4 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m00:01\u001b[0m00:01\u001b[0m\n\u001b[?25hRequirement already satisfied: tqdm in /opt/conda/lib/python3.7/site-packages (from kaggle->-r /kaggle/working/kaggle/requirements/main.in (line 1)) (4.64.0)\nRequirement already satisfied: six>=1.10 in /opt/conda/lib/python3.7/site-packages (from kaggle->-r /kaggle/working/kaggle/requirements/main.in (line 1)) (1.16.0)\nRequirement already satisfied: python-dateutil in /opt/conda/lib/python3.7/site-packages (from kaggle->-r /kaggle/working/kaggle/requirements/main.in (line 1)) (2.8.2)\nRequirement already satisfied: python-slugify in /opt/conda/lib/python3.7/site-packages (from kaggle->-r /kaggle/working/kaggle/requirements/main.in (line 1)) (6.1.2)\nRequirement already satisfied: certifi in /opt/conda/lib/python3.7/site-packages (from kaggle->-r /kaggle/working/kaggle/requirements/main.in (line 1)) (2022.6.15)\nRequirement already satisfied: urllib3 in /opt/conda/lib/python3.7/site-packages (from kaggle->-r /kaggle/working/kaggle/requirements/main.in (line 1)) (1.26.9)\nRequirement already satisfied: requests in /opt/conda/lib/python3.7/site-packages (from kaggle->-r /kaggle/working/kaggle/requirements/main.in (line 1)) (2.27.1)\nRequirement already satisfied: numpy>=1.14.5 in /opt/conda/lib/python3.7/site-packages (from opencv-python->-r /kaggle/working/kaggle/requirements/main.in (line 2)) (1.21.6)\nRequirement already satisfied: Pillow in /opt/conda/lib/python3.7/site-packages (from openslide-python->-r /kaggle/working/kaggle/requirements/main.in (line 3)) (9.1.1)\nRequirement already satisfied: pytz>=2017.3 in /opt/conda/lib/python3.7/site-packages (from pandas->-r /kaggle/working/kaggle/requirements/main.in (line 4)) (2022.1)\nRequirement already satisfied: typing-extensions in /opt/conda/lib/python3.7/site-packages (from torch->-r /kaggle/working/kaggle/requirements/main.in (line 5)) (4.1.1)\nRequirement already satisfied: packaging in /opt/conda/lib/python3.7/site-packages (from torchmetrics->-r /kaggle/working/kaggle/requirements/main.in (line 6)) (21.3)\nRequirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /opt/conda/lib/python3.7/site-packages (from packaging->torchmetrics->-r /kaggle/working/kaggle/requirements/main.in (line 6)) (3.0.9)\nRequirement already satisfied: text-unidecode>=1.3 in /opt/conda/lib/python3.7/site-packages (from python-slugify->kaggle->-r /kaggle/working/kaggle/requirements/main.in (line 1)) (1.3)\nRequirement already satisfied: charset-normalizer~=2.0.0 in /opt/conda/lib/python3.7/site-packages (from requests->kaggle->-r /kaggle/working/kaggle/requirements/main.in (line 1)) (2.0.12)\nRequirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.7/site-packages (from requests->kaggle->-r /kaggle/working/kaggle/requirements/main.in (line 1)) (3.3)\nInstalling collected packages: torch, opencv-python, torchvision\n  Attempting uninstall: torch\n    Found existing installation: torch 1.11.0\n    Uninstalling torch-1.11.0:\n      Successfully uninstalled torch-1.11.0\n  Attempting uninstall: opencv-python\n    Found existing installation: opencv-python 4.5.4.60\n    Uninstalling opencv-python-4.5.4.60:\n      Successfully uninstalled opencv-python-4.5.4.60\n  Attempting uninstall: torchvision\n    Found existing installation: torchvision 0.12.0\n    Uninstalling torchvision-0.12.0:\n      Successfully uninstalled torchvision-0.12.0\n\u001b[31mERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\nfastai 2.7.4 requires torch<1.12,>=1.7.0, but you have torch 1.12.0 which is incompatible.\nallennlp 2.9.3 requires torch<1.12.0,>=1.6.0, but you have torch 1.12.0 which is incompatible.\nallennlp 2.9.3 requires torchvision<0.13.0,>=0.8.1, but you have torchvision 0.13.0 which is incompatible.\u001b[0m\u001b[31m\n\u001b[0mSuccessfully installed opencv-python-4.6.0.66 torch-1.12.0 torchvision-0.13.0\n\u001b[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\u001b[0m\u001b[33m\n\u001b[0m","output_type":"stream"}]},{"cell_type":"code","source":"!git pull","metadata":{"execution":{"iopub.status.busy":"2022-07-19T02:34:33.451697Z","iopub.execute_input":"2022-07-19T02:34:33.452105Z","iopub.status.idle":"2022-07-19T02:34:34.203161Z","shell.execute_reply.started":"2022-07-19T02:34:33.452073Z","shell.execute_reply":"2022-07-19T02:34:34.201872Z"},"trusted":true},"execution_count":null,"outputs":[]},{"cell_type":"code","source":"from glob import glob\n\nimport pandas as pd\nimport torch\nfrom torch.utils.data import DataLoader\nfrom torchmetrics import MetricCollection\nfrom torchmetrics.classification import Accuracy\nfrom torchmetrics.classification import CalibrationError\nfrom torchvision.models import densenet161\n\nfrom mayo_clinic_strip_ai.dataset import TifDataset\nfrom mayo_clinic_strip_ai.model import Classifier\nfrom mayo_clinic_strip_ai.model import FeatureExtractor\nfrom mayo_clinic_strip_ai.model import Loss\nfrom mayo_clinic_strip_ai.model import Model\nfrom mayo_clinic_strip_ai.model import Normalizer\nfrom mayo_clinic_strip_ai.metadata import load_metadata\nfrom multiprocessing import cpu_count\n\n\ntorch.backends.cudnn.benchmark = True\n\ntrain_meta = pd.merge(\n    left=pd.read_csv(\"/kaggle/input/mayo-rois/train/ROIs.csv\"),\n    right=load_metadata(\"/kaggle/input/mayo-clinic-strip-ai/train.csv\"),\n    how=\"left\",\n    validate=\"m:1\",\n    on=\"image_id\",\n)\n\nmodel = Model(\n    normalizer=Normalizer(),\n    feature_extractor=FeatureExtractor(backbone=densenet161()),\n    classifier=Classifier(initial_logit_bias=0.0, in_features=2208),  # FIXME: auto-set in_features\n)\noptimizer = torch.optim.AdamW(model.parameters(), lr=2e-3, weight_decay=0.1)\nloss_fn = Loss(pos_weight=0.5)  # FIXME: compute pos_weight from data\nmetrics = MetricCollection(Accuracy(), CalibrationError())\n\n# move things to the right device\ndevice = torch.device(\"cuda\", 0) if torch.cuda.is_available() else torch.device(\"cpu\")\nprint(\"Device\", device)\nmodel.to(device=device, memory_format=torch.channels_last, non_blocking=True)\nloss_fn.to(device=device, non_blocking=True)\nmetrics.to(device=device, non_blocking=True)\n\ntrain_dataset = TifDataset(\n    metadata=train_meta,\n    training=True,\n    data_dir=\"/kaggle/input/mayo-clinic-strip-ai/train/\",\n)\nbatch_size = 16\nnum_workers = cpu_count()\nprefetch_batches = 4\ntrain_dataloader = DataLoader(\n    dataset=train_dataset,\n    batch_size=batch_size,\n    shuffle=True,\n    pin_memory=torch.cuda.is_available(),\n    pin_memory_device=str(device),\n    prefetch_factor=max(2, prefetch_batches * batch_size // num_workers),\n    num_workers=num_workers,\n    drop_last=torch.backends.cudnn.benchmark,\n)\n\ngrad_scaler = torch.cuda.amp.GradScaler()\n\nprint(\"num workers\", num_workers)\nprint(\"prefetch factor\", train_dataloader.prefetch_factor)\nfor epoch in range(10):\n    print(\"Starting epoch\", epoch)\n    for img, label_id in train_dataloader:\n        img = img.to(device=device, memory_format=torch.channels_last, non_blocking=True)\n        label_id = label_id.to(device=device, non_blocking=True)\n        with torch.autocast(device_type=img.device.type):\n            optimizer.zero_grad(set_to_none=True)\n            logit: torch.Tensor = model(img)\n            loss: torch.Tensor = loss_fn(logit=logit, label=label_id)\n            grad_scaler.scale(loss).backward()\n            grad_scaler.step(optimizer)\n            grad_scaler.update()\n            metrics.update(preds=logit.sigmoid(), target=label_id)\n            m = {k: v.item() for k, v in metrics.compute().items()}\n            metrics.reset()\n        print(m)","metadata":{"execution":{"iopub.status.busy":"2022-07-19T03:23:41.040094Z","iopub.execute_input":"2022-07-19T03:23:41.042436Z"},"trusted":true},"execution_count":null,"outputs":[{"name":"stderr","text":"[autoreload of pkg_resources failed: Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 245, in check\n    superreload(m, reload, self.old_objects)\n  File \"/opt/conda/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n    module = reload(module)\n  File \"/opt/conda/lib/python3.7/imp.py\", line 314, in reload\n    return importlib.reload(module)\n  File \"/opt/conda/lib/python3.7/importlib/__init__.py\", line 169, in reload\n    _bootstrap._exec(spec, module)\n  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n  File \"/opt/conda/lib/python3.7/site-packages/pkg_resources/__init__.py\", line 74, in <module>\n    from pkg_resources.extern.jaraco.text import (\nModuleNotFoundError: No module named 'pkg_resources.extern.jaraco'\n]\n","output_type":"stream"},{"name":"stdout","text":"Device cuda:0\nnum workers 2\nprefetch factor 32\nStarting epoch 0\n{'Accuracy': 0.375, 'CalibrationError': 0.1881103515625}\n{'Accuracy': 0.5, 'CalibrationError': 0.2452802211046219}\n{'Accuracy': 0.625, 'CalibrationError': 0.1963958740234375}\n{'Accuracy': 0.4375, 'CalibrationError': 0.5358295440673828}\n{'Accuracy': 0.8125, 'CalibrationError': 0.18795537948608398}\n{'Accuracy': 0.6875, 'CalibrationError': 0.2509284019470215}\n{'Accuracy': 0.6875, 'CalibrationError': 0.20892858505249023}\n{'Accuracy': 0.6875, 'CalibrationError': 0.17264682054519653}\n{'Accuracy': 0.6875, 'CalibrationError': 0.17568445205688477}\n{'Accuracy': 0.8125, 'CalibrationError': 0.07723760604858398}\n{'Accuracy': 0.75, 'CalibrationError': 0.1724081039428711}\n{'Accuracy': 0.6875, 'CalibrationError': 0.12208367884159088}\n{'Accuracy': 0.75, 'CalibrationError': 0.21883773803710938}\n{'Accuracy': 0.625, 'CalibrationError': 0.20199203491210938}\n{'Accuracy': 0.625, 'CalibrationError': 0.1725006252527237}\n","output_type":"stream"}]},{"cell_type":"code","source":"","metadata":{},"execution_count":null,"outputs":[]}]}